config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  namespace :admin do
    resources :deposit_sources do as_routes end
    resources :mineral_resources do as_routes end
    resources :deposit_resources do as_routes end
    resources :pages do as_routes end
    resources :social_projects do as_routes end
    resources :processing_infrastructures do as_routes end
    resources :deposits do as_routes end

    resources :employees do as_routes end
    resources :flows_payable_under_contracts do as_routes end
    resources :report_relations do as_routes end
    resources :categories do as_routes end
    resources :sources do as_routes end
    resources :authors do as_routes end
    resources :attachments do as_routes end
    resources :reports do
      as_routes
      as_nested_resources :attachments
    end
    resources :stock_exchange_countries do as_routes end
    resources :stock_exchanges do as_routes end

    resources :shareholders do as_routes end
    resources :shareholder_relationships do as_routes end
    resources :intermediary_companies do as_routes end
    resources :shareholder_intermediaries do as_routes end

    resources :env_and_social_obligations do as_routes end
    resources :tax_obligations do as_routes end
    resources :production_exports do as_routes end
    resources :drc_companies do as_routes end

    resources :special_reports do as_routes end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/admin', to: redirect('admin/drc_companies')
  get '/about', to: 'static_pages#about'
  get '/rapport-gecamines', to: 'static_pages#specialreport'

  resources :drc_companies, only: %i[show index] do # , only: [:show, :index]
    member do
      get 'get_geodata'
      get 'get_deposits_geodata'
      get 'get_processing_infrastructures_geodata'
      get 'get_social_projects_geodata'
    end
  end
  resources :reports, only: %i[show index]
  resources :shareholders, only: %i[show index]
  resources :categories, only: :show do
  end

  resources :pages, only: :show

  resource :search, only: :show

  resource :map do
    member do
      get 'get_all_deposits'
      get 'get_all_processing_infrastructures'
      get 'get_all_social_projects'
    end
  end

  get '/sitemap.xml' => 'sitemap#index', :format => 'xml', :as => :sitemap

end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def show; end

  def get_all_deposits
    @deposits = Deposit.all
  end

  def get_all_processing_infrastructures
    @processing_infrastructures = ProcessingInfrastructure.all
  end

  def get_all_social_projects
    @social_projects = SocialProject.all
  end
end

app/views/maps/_map_nav.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: true">

  <ul class="title-area">
    <li class="name"><!-- Leave this empty --></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <ul class="left">

      <li class="has-dropdown map-dropdown baselayers">
        <a class="title" href="#">Couche de base <span class="layer-title"></span></a>
        <ul class="dropdown">
          <li>
            <a class="add-layer" data-id="terrain" href="#">Terrain</a>
          </li>
          <li>
            <a class="add-layer" data-id="satellite" href="#">Satellite</a>
          </li>
        </ul>
      </li>

      <li class="divider"></li>

      <li class="has-dropdown map-dropdown mining-data">
        <a class="title" href="#">Mines et infrastructures <span class="layer-title"></span></a>
        <ul class="dropdown">
          <li>
            <a class="add-layer" href="#" data-type="deposit" data-url="<%= get_all_deposits_map_url %>"><%= t('gisements') %></a>
          </li>
          <li>
            <a class="add-layer" href="#" data-type="processing_infrastructure" data-url="<%= get_all_processing_infrastructures_map_url %>"><%= t('installations_de_traitement') %></a>
          </li>
          <li>
            <a class="add-layer" href="#" data-type="social_project" data-url="<%= get_all_social_projects_map_url %>"><%= t('projets_sociaux') %></a>
          </li>
        </ul>
      </li>

      <li class="divider"></li>

      <li class="has-dropdown map-dropdown maps">
        <a class="title" href="#">Concessions <span class="layer-title"></span></a>
        <ul class="dropdown">
          <% TileLayer.all.each do |tile| %>
            <li>
              <a class="add-layer" href="#" data-id="<%= tile.mapbox_tile_layer %>"><%= tile.label %></a>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="divider"></li>
    </ul>

  </section>
</nav>

app/views/maps/show.html.slim
div.map
  
  = render "map_nav"
  div#map

javascript:
  $(function() {
    app.initMap();

    // set baselayer
    $('.top-bar .baselayers a.add-layer[data-id="terrain"]').trigger('click');

    // show deposits
    $('.top-bar a.add-layer[data-type="deposit"]').trigger('click');
  });