config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  namespace :admin do
    resources :deposit_sources do as_routes end
    resources :mineral_resources do as_routes end
    resources :deposit_resources do as_routes end
    resources :pages do as_routes end
    resources :social_projects do as_routes end
    resources :processing_infrastructures do as_routes end
    resources :deposits do as_routes end

    resources :employees do as_routes end
    resources :flows_payable_under_contracts do as_routes end
    resources :report_relations do as_routes end
    resources :categories do as_routes end
    resources :sources do as_routes end
    resources :authors do as_routes end
    resources :attachments do as_routes end
    resources :reports do
      as_routes
      as_nested_resources :attachments
    end
    resources :stock_exchange_countries do as_routes end
    resources :stock_exchanges do as_routes end

    resources :shareholders do as_routes end
    resources :shareholder_relationships do as_routes end
    resources :intermediary_companies do as_routes end
    resources :shareholder_intermediaries do as_routes end

    resources :env_and_social_obligations do as_routes end
    resources :tax_obligations do as_routes end
    resources :production_exports do as_routes end
    resources :drc_companies do as_routes end

    resources :special_reports do as_routes end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/admin', to: redirect('admin/drc_companies')
  get '/about', to: 'static_pages#about'
  get '/rapport-gecamines', to: 'static_pages#specialreport'

  resources :drc_companies, only: %i[show index] do # , only: [:show, :index]
    member do
      get 'get_geodata'
      get 'get_deposits_geodata'
      get 'get_processing_infrastructures_geodata'
      get 'get_social_projects_geodata'
    end
  end
  resources :reports, only: %i[show index]
  resources :shareholders, only: %i[show index]
  resources :categories, only: :show do
  end

  resources :pages, only: :show

  resource :search, only: :show

  resource :map do
    member do
      get 'get_all_deposits'
      get 'get_all_processing_infrastructures'
      get 'get_all_social_projects'
    end
  end

  get '/sitemap.xml' => 'sitemap#index', :format => 'xml', :as => :sitemap

end

app/models/drc_company.rb
# frozen_string_literal: true

class DrcCompany < ActiveRecord::Base
  # include FriendlyId
  # friendly_id :name #, :use => [:slugged] #, :simple_i18n]

  has_many :production_exports, dependent: :destroy
  has_many :tax_obligations, dependent: :destroy

  has_many :shareholder_relationships, dependent: :destroy
  has_many :shareholders, through: :shareholder_relationships

  has_many :report_relations, dependent: :destroy
  has_many :reports, through: :report_relations, dependent: :destroy

  has_many :social_projects, dependent: :destroy

  has_many :processing_infrastructures, dependent: :destroy
  has_many :deposits, dependent: :destroy

  has_many :employees, dependent: :destroy

  has_one :flows_payable_under_contract, dependent: :destroy
  has_one :env_and_social_obligation, dependent: :destroy

  has_one :page, dependent: :destroy

  # validates_presence_of :name #, :legal_status, :project_phase, :project_type, :acronym, :contact

  validates :name, uniqueness: true, presence: true

  paginates_per 30

  def to_label
    try(:name)
  end

  searchable do
    text :name, boost: 5

    text :description, :acronym, :nrc, :rccm, :contact, :website, :legal_status,
         :legal_status, :project_type, :project_phase, :legal_regime, :permits

    # time reports do
    #  time :published_at
    # string :publish_month
    text :reports do
      reports.pluck(:summary)
    end

    # time :published_at
    # string :publish_month
  end

  def to_param
    "#{id}-#{name.try(:parameterize)}" if id
  end
end

app/controllers/admin/drc_companies_controller.rb
# frozen_string_literal: true

class Admin::DrcCompaniesController < Admin::Auth
  active_scaffold :drc_company do |config|
    config.label = I18n.t 'controllers.admin.drccompanies.label'

    # Export
    config.actions.add :export
    config.export.force_quotes = 'true'
    config.export.force_quotes = 'true'

    config.columns = %i[name description acronym nrc rccm contact website
                        legal_status project_type project_phase legal_regime permits
                        flows_payable_under_contract tax_obligations production_exports
                        shareholder_relationships employees
                        env_and_social_obligation processing_infrastructures social_projects]

    # you can define a default values for the exporting form
    # config.export.default_deselected_columns = %w(phone address)

    config.list.per_page = 25
    config.list.sorting = { name: :asc }

    config.list.columns = %i[name acronym nrc rccm contact website
                             legal_status project_type project_phase legal_regime permits deposits]

    #     config.update.columns = [:name, :description, :acronym,  :nrc, :rccm,:contact, :website,
    #       :legal_status, :project_type, :project_phase, :legal_regime, :permits,
    #       :flows_payable_under_contract, :tax_obligations,  :production_exports,
    #       :shareholder_relationships, :employees,
    #       :env_and_social_obligation, :processing_infrastructures, :social_projects]
    #
    #     config.export.columns = [:name, :acronym, :description, :nrc, :rccm,:contact, :website,
    #         :legal_status, :project_type, :project_phase, :legal_regime, :permits,
    #         :flows_payable_under_contract, :tax_obligations,  :production_exports,
    #         :shareholder_relationships, :employees,
    #         :env_and_social_obligation, :deposits, :processing_infrastructures, :social_projects]

    config.columns[:permits].form_ui = :textarea

    config.columns[:shareholder_relationships].allow_add_existing = false
    config.columns[:social_projects].allow_add_existing = false

    config.nested.add_link(:reports, label: 'Documents')
    config.nested.add_link(:deposits, label: 'Gisements')

    # config.columns[:tax_obligations].label = 'Tax Payments'

    config.columns[:legal_regime].form_ui = :select
    config.columns[:legal_regime].options = {
      include_blank: 'Sélectionnez Statut juridique',
      options: ['Convention',
                'Code minier 2002',
                'Code minier révisé']
    }

    config.columns[:legal_status].form_ui = :select
    config.columns[:legal_status].options = {
      include_blank: 'Sélectionnez Statut juridique',
      options: %w[SPRL SARL]
    }

    config.columns[:project_type].form_ui = :select
    config.columns[:project_type].options = {
      include_blank: 'Sélectionnez le type de projet',
      options: %w[Industriel Semi-industriel
                  Artisanal]
    }

    config.columns[:project_phase].form_ui = :select
    config.columns[:project_phase].options = {
      include_blank: 'Sélectionnez la phase de projet',
      options: %w[dormant exploration construction exploitation fermé]
    }
  end
end

app/controllers/drc_companies_controller.rb
# frozen_string_literal: true

# Companies
class DrcCompaniesController < ApplicationController
  before_action :company, only: [:show]
  before_action :employees_by_year, only: [:show]
  before_action :production_exports_by_year, only: [:show]
  before_action :tax_obligations_by_year, only: [:show]

  def show
    @drc_company_reports = @drc_company.reports.order(actual_post_date: :desc)
                                       .page(params[:page]).per(12)
  end

  def company
    @drc_company = DrcCompany.includes(
      :tax_obligations, :employees, :deposits, :processing_infrastructures, :social_projects,
      :env_and_social_obligation, :flows_payable_under_contract,
      :production_exports
    ).find(params[:id])
  end

  def employees_by_year
    @drc_company_employees_years = []
    @drc_company_employees_byyear = {}
    @drc_company.employees.each do |employee|
      @year = employee.year
      unless @drc_company_employees_byyear[@year]
        @drc_company_employees_byyear[@year] = []
        @drc_company_employees_years.push(@year)
      end
      @drc_company_employees_byyear[@year].push(employee)
    end
  end

  def production_exports_by_year
    @drc_company_production_exports_years = []
    @drc_company_production_exports_byyear = {}
    @drc_company.production_exports.each do |pe|
      @year = pe.year
      unless @drc_company_production_exports_byyear[@year]
        @drc_company_production_exports_byyear[@year] = []
        @drc_company_production_exports_years.push(@year)
      end
      @drc_company_production_exports_byyear[@year].push(pe)
    end
  end

  def tax_obligations_by_year
    @drc_company_tax_obligations_years = []
    @drc_company_tax_obligations_byyear = {}
    @drc_company.tax_obligations.each do |to|
      @year = to.year
      unless @drc_company_tax_obligations_byyear[@year]
        @drc_company_tax_obligations_byyear[@year] = []
        @drc_company_tax_obligations_years.push(@year)
      end
      @drc_company_tax_obligations_byyear[@year].push(to)
    end
  end

  def index
    # make one ivar for all companies for select dropdown
    # make one ivar for paginated list
    @all_drc_companies = DrcCompany.all.order('name ASC')
    @drc_companies = DrcCompany.all.order('name ASC').page params[:page]
    @all_shareholders = Shareholder.all.order('name ASC')
    @shareholders = Shareholder.all.order('name ASC').page params[:page]
    render :index
  end
  skip_before_action :verify_authenticity_token
  def get_geodata
    # get_geodata_drc_company_path(@drc_company)
    @drc_company = DrcCompany.includes(:deposits, :social_projects,
                                       :processing_infrastructures).find(params[:id])
    # render :json
  end

  def get_deposits_geodata
    @drc_company = DrcCompany.includes(:deposits).find(params[:id])
  end

  def get_social_projects_geodata
    @drc_company = DrcCompany.includes(:social_projects).find(params[:id])
  end

  def get_processing_infrastructures_geodata
    @drc_company = DrcCompany.includes(:processing_infrastructures).find(params[:id])
  end

  private

  def drc_company_params; end
end

app/helpers/admin/drc_companies_helper.rb
# frozen_string_literal: true

# creates a popup link to page link
module Admin::DrcCompaniesHelper
  def drc_company_name_column(record, _column)
    link_to(record.try(:name), record, target: '_blank', rel: 'noopener')
  end

  def drc_company_website_column(record, _column)
    link_to(record.try(:website), record.try(:website), target: '_blank', rel: 'noopener') if record.website.present?
  end
end

app/views/drc_companies/_company_map_nav.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: true">

  <ul class="title-area">
    <li class="name"><!-- Leave this empty --></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">

      <li class="divider"></li>
      

      <li class="has-dropdown map-dropdown mining-data">
        <a class="title" href="#"><%= t('mines_et_infrastructures') %><span class="layer-title"></span></a>
        <ul class="dropdown">
          <% if @drc_company.deposits.count > 0 %>
            <li>
              <a class="add-layer" href="#" data-type="deposit" data-url="<%= get_deposits_geodata_drc_company_path{@drc_company} %>"><%= t('gisements') %></a>
            </li>
          <% end %>
          <% if @drc_company.processing_infrastructures.count > 0 %>
            <li>
              <a class="add-layer" href="#" data-type="processing_infrastructure" data-url="<%= get_processing_infrastructures_geodata_drc_company_path{@drc_company} %>"><%= t('installations_de_traitement') %></a>
            </li>
          <% end %>
          <% if @drc_company.social_projects.count > 0 %>
            <li>
              <a class="add-layer" href="#" data-type="social_project" data-url="<%= get_social_projects_geodata_drc_company_path{@drc_company} %>"><%= t('projets_sociaux') %></a>
            </li>
          <% end %>
        </ul>
      </li>

     

      <li class="divider"></li>
    </ul>

  </section>
</nav>
<iframe id="map"  src="<%= ENV['MAPHUBS_EMBED_LINK'] %>"
  frameborder="0" allowFullScreen="true" webkitallowfullscreen="true" mozallowfullscreen="true">
</iframe>

app/views/drc_companies/index.html.slim
title=title
div.row.keyline-bottom.pbl
  div.small-12.columns
    h1.quiet= t('.rechercher_une_soci_t')

  form action="../"
    div.small-12.medium-6.columns
      div.row.collapse
        label for="company"= t('.company_label')
        div.small-10.columns
          select#company.select2-dropdown name="drc_company_nav"
            option
            - @all_drc_companies.each do |c|
              option value="#{drc_company_url(c)}" = c.name

        div.small-2.columns
          input.button.postfix [type="button" name="t('.soumettre')"
            onClick="window.open(drc_company_nav.value, '_self')" value=="&#x1F50D"]
          / take out '_self' argument to open company page in new tab
          /a.button.postfix[href="#"] X


  form action="../"
    div.small-12.medium-6.columns
      div.row.collapse
        label for="shareholder"= t('.investisseurs')
        div.small-10.columns
          select#shareholder.select2-dropdown name="shareholder_nav"
            option
            - @all_shareholders.each do |c|
              option value="#{shareholder_url(c)}" = c.name

        div.small-2.columns
          input.button.postfix [type="button" name="t('.soumettre')"
            onClick="window.open(shareholder_nav.value, '_self')" value=="&#x1F50D"]
          / a.button.postfix[href="#"] X

div.row.pvl
  div.large-6.columns
    - @drc_companies.each do |company|
      div.company
        h4
          a href="#{drc_company_url(company)}" = company.name
          - if company.acronym?
            |  (
            span.quiet = company.acronym
            | )

  div.large-6.columns
    - @shareholders.each do |shareholder|
      div.company
        h4
          a href="#{shareholder_url(shareholder)}" = shareholder.name
          - if shareholder.acronym?
            |  (
            span.quiet = shareholder.acronym
            | )



div.row
  div.large-6.columns
    = paginate @drc_companies

  div.large-6.columns
    = paginate @shareholders