config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  namespace :admin do
    resources :deposit_sources do as_routes end
    resources :mineral_resources do as_routes end
    resources :deposit_resources do as_routes end
    resources :pages do as_routes end
    resources :social_projects do as_routes end
    resources :processing_infrastructures do as_routes end
    resources :deposits do as_routes end

    resources :employees do as_routes end
    resources :flows_payable_under_contracts do as_routes end
    resources :report_relations do as_routes end
    resources :categories do as_routes end
    resources :sources do as_routes end
    resources :authors do as_routes end
    resources :attachments do as_routes end
    resources :reports do
      as_routes
      as_nested_resources :attachments
    end
    resources :stock_exchange_countries do as_routes end
    resources :stock_exchanges do as_routes end

    resources :shareholders do as_routes end
    resources :shareholder_relationships do as_routes end
    resources :intermediary_companies do as_routes end
    resources :shareholder_intermediaries do as_routes end

    resources :env_and_social_obligations do as_routes end
    resources :tax_obligations do as_routes end
    resources :production_exports do as_routes end
    resources :drc_companies do as_routes end

    resources :special_reports do as_routes end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/admin', to: redirect('admin/drc_companies')
  get '/about', to: 'static_pages#about'
  get '/rapport-gecamines', to: 'static_pages#specialreport'

  resources :drc_companies, only: %i[show index] do # , only: [:show, :index]
    member do
      get 'get_geodata'
      get 'get_deposits_geodata'
      get 'get_processing_infrastructures_geodata'
      get 'get_social_projects_geodata'
    end
  end
  resources :reports, only: %i[show index]
  resources :shareholders, only: %i[show index]
  resources :categories, only: :show do
  end

  resources :pages, only: :show

  resource :search, only: :show

  resource :map do
    member do
      get 'get_all_deposits'
      get 'get_all_processing_infrastructures'
      get 'get_all_social_projects'
    end
  end

  get '/sitemap.xml' => 'sitemap#index', :format => 'xml', :as => :sitemap

end

app/views/layouts/admin/_flash.html.slim
- if notice.present?
  div.alert.alert-success.alert-dismissable
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    =notice
- if alert.present?
  div.alert.alert-dismissable.alert-danger
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    = alert

app/views/layouts/admin/_navigation.html.slim
.header
  ul.nav.nav-pills.pull-right

    li[class="#{active?(admin_drc_companies_path)}"] = link_to "RDC Entreprises", admin_drc_companies_path
    li[class="#{active?(admin_mineral_resources_path)}"] = link_to "Minerais", admin_mineral_resources_path
    li[class="#{active?(admin_shareholders_path)}"] = link_to "Actionnaire", admin_shareholders_path
    li[class="#{active?(admin_reports_path)}"] = link_to "Documents", admin_reports_path
    li[class="#{active?(admin_sources_path)}"] = link_to "Sources", admin_sources_path
    / li = link_to "Minerals", admin_mineral_resources_path
    li[class="#{active?(admin_intermediary_companies_path)}"] = link_to "Enterpries Intermédiaires", admin_intermediary_companies_path
    li[class="#{active?(admin_pages_path)}"] = link_to "Pages", admin_pages_path
    li[class="#{active?(admin_special_reports_path)}"] = link_to "Pages Spécial", admin_special_reports_path
    / li = link_to "Deposit Sources", admin_deposit_sources_path
    / li = link_to "Categories", admin_categories_path


  h3.text-muted
    = link_to "Congo Mines", root_path

app/views/layouts/admin/auth.html.slim
doctype html
html
  head
    = tag 'meta', 'charset' => 'utf-8'
    title CongoMines | v1.2
    / = stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
    = stylesheet_link_tag    "bootstrap.min.css"
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "admin", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .container-fluid
      = render "layouts/admin/navigation"
      = render "layouts/admin/flash"
      = yield