config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  namespace :admin do
    resources :deposit_sources do as_routes end
    resources :mineral_resources do as_routes end
    resources :deposit_resources do as_routes end
    resources :pages do as_routes end
    resources :social_projects do as_routes end
    resources :processing_infrastructures do as_routes end
    resources :deposits do as_routes end

    resources :employees do as_routes end
    resources :flows_payable_under_contracts do as_routes end
    resources :report_relations do as_routes end
    resources :categories do as_routes end
    resources :sources do as_routes end
    resources :authors do as_routes end
    resources :attachments do as_routes end
    resources :reports do
      as_routes
      as_nested_resources :attachments
    end
    resources :stock_exchange_countries do as_routes end
    resources :stock_exchanges do as_routes end

    resources :shareholders do as_routes end
    resources :shareholder_relationships do as_routes end
    resources :intermediary_companies do as_routes end
    resources :shareholder_intermediaries do as_routes end

    resources :env_and_social_obligations do as_routes end
    resources :tax_obligations do as_routes end
    resources :production_exports do as_routes end
    resources :drc_companies do as_routes end

    resources :special_reports do as_routes end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/admin', to: redirect('admin/drc_companies')
  get '/about', to: 'static_pages#about'
  get '/rapport-gecamines', to: 'static_pages#specialreport'

  resources :drc_companies, only: %i[show index] do # , only: [:show, :index]
    member do
      get 'get_geodata'
      get 'get_deposits_geodata'
      get 'get_processing_infrastructures_geodata'
      get 'get_social_projects_geodata'
    end
  end
  resources :reports, only: %i[show index]
  resources :shareholders, only: %i[show index]
  resources :categories, only: :show do
  end

  resources :pages, only: :show

  resource :search, only: :show

  resource :map do
    member do
      get 'get_all_deposits'
      get 'get_all_processing_infrastructures'
      get 'get_all_social_projects'
    end
  end

  get '/sitemap.xml' => 'sitemap#index', :format => 'xml', :as => :sitemap

end

app/views/shared/_auth.html.erb
<input type="hidden" name="authenticity_token"
       value="<%= form_authenticity_token %>">

app/views/shared/_banner.html.slim
div.banner
  div.row
    div.large-8.columns: h2= t('.view_collection')
    div.large-4.columns: a href="#{reports_url}"= t('.visit_library')

app/views/shared/_documents.html.slim
div.small-12.columns
  div[class="document-container medium-block-grid-#{columns}"]
    - if reports
      - reports.each do |rpt|
        - unless rpt.nil?
          li
            article[class="hide-summary-#{hide_summary}" lang="fr"]
              h3.doc-title = link_to rpt.try(:title), rpt
              h4.doc-source = rpt.try(:source).try(:name)
              / p.doc-date = rpt.try(:date_string).try(:titleize)
              - if rpt.actual_post_date
                p.doc-date = l(rpt.actual_post_date.to_date, format: :month_and_year)

              - if rpt.summary.present?
                p.doc-summary =truncate_summary(rpt.summary, 300).html_safe

                - if hide_summary
                  a[href="#" class="show-summary"]= t('.afficher_le_resume')

app/views/shared/_search.html.slim
div.search.pbl
  / form action="#{search_url}" method="get"
  / = form_tag search_path, :method => :get do

  div.row
    div.large-12.columns.text-center
      h1 = t('.header') 

  = form_tag search_path, :method => :get do
    div.row
      div.small-12.columns
        div.row.collapse
          div.small-10.columns
            - @placeholder =  @search_params.blank? ? (t('.empty_search_message')) : @search_params
            = text_field_tag :search, params[:q], { placeholder: @placeholder}

          div.small-2.columns
            button.postfix= t('.rechercher')
            /a.button.postfix[href="a"]= t('.rechercher')

        a#hideshow value="wee" =(t('.naviguer'))

    div#browse-search.clearfix
      div.row
        div.medium-3.columns
          label for="theme" = t('.theme')
          select#theme name="theme"
            option
            - root = Category.find(26)
            - root.children.each do |subtheme|
              - subtheme.children.each do |theme|
                option value="#{theme.id}" = theme.name

        div.medium-3.columns
          label for="type_document" = t('.type_de_document')
          select#type_document name="type_document"
            option
            - type_doc = Category.find(1)
            - type_doc.children.each do |type|
              option value="#{type.id}" = type.name

        div.medium-3.columns
          label for="type_source" = t('.type_de_source')
          select#type_source name="type_source"
            option
            - type_src = Category.find(14)
            - type_src.children.each do |type|
              option value="#{type.id}" = type.name

        div.medium-3.columns
          label for="province" = t('.province')
          select#province name="province"
            option
            - province = Category.find(54)
            - province.children.each do |p|
              option value="#{p.id}" = p.name

      div.row
        div.large-12.columns
          button = t('.soumettre')